/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AsyncConsumer */

#ifndef _Included_AsyncConsumer
#define _Included_AsyncConsumer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AsyncConsumer
 * Method:    jni_proc_msg
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AsyncConsumer_jni_1proc_1msg
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
