/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testjni */

#ifndef _Included_testjni
#define _Included_testjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testjni
 * Method:    post_msg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testjni_post_1msg
  (JNIEnv *, jclass);




#ifdef __cplusplus
}
#endif
#endif
